### ISSUE TITLE
enforce compilation

### ISSUE THREAD

**Issue by Dierk** [tricktron/frege-vscode#8]
sometimes, I want to enforce compilation without actually running the code (there might not even be a main function).
What is the best way to enforce this? on save, after change plus waiting time, keystroke, intention?
ATM, I can only "run" or use the terminal to start the gradle task myself.

**Comment by tricktron** [comment]
There are two tools involved that you interact with:

1. The https://github.com/tricktron/frege-lsp-server automatically recompiles the currently open frege file whenever you save it and shows you hover and compiler errors. That means, if you have autosave enabled in vscode it compiles the file in the background every few seconds, which is bad and good.
2. The https://github.com/tricktron/frege-gradle-plugin, which is used if you click on the `Run` overlay of the main function.

### Roadmap

The long term goal is to include everything into 1. The short term goal is to add more functionality to the plugin quickly, so that it becomes more usable. Therefore, I started to make use of the https://github.com/tricktron/frege-gradle-plugin. Especially the upcoming `repl` feature looks promising because then you can interact with your code in the frege reply.

Enforcing compilation to 2. could be added by:
- A button in the top right, that triggers the `compileFrege` task
- A shortcut key binding that triggers the `compileFrege` task

I am open to more options if you can think of something else.

**Comment by Dierk** [comment]
I think both options would work - even having both at the same time.
It would be good to follow the same approach that other languages use such that vs-code users find their usual way. I guess that means having an "action" with optional keybinding that appears in the cmd-shift-p dialog?

**Comment by tricktron** [comment]
> I guess that means having an "action" with optional keybinding that appears in the cmd-shift-p dialog?

Exactly.
